export const marketingBootstrap = {
  brand: {
    name: "House of Prax",
    shorthand: "HOP",
    tagline: "Natural Energy - Engineered for Performance",
    subtext:
      "Premium plant-based nutrition and wellness shots designed for the uncompromising athlete.",
    contact: {
      whatsapp: ["08060785487", "07019719537"],
      instagram: "house_of_prax",
    },
  },
  navigation: [
    { label: "Products", href: "#shop" },
    { label: "Ingredients", href: "#ingredients" },
    { label: "Experience", href: "#lifestyle" },
  ],
  benefits: [
    {
      title: "100% Organic",
      description: "Cleanest sources, zero chemical fillers or artificial additives.",
      icon: "Leaf",
    },
    {
      title: "Gut Health First",
      description: "Probiotics and plant enzymes for peak nutrient absorption.",
      icon: "Activity",
    },
    {
      title: "Performance Fuel",
      description: "18g protein per serving to support muscle and recovery.",
      icon: "Zap",
    },
    {
      title: "Zero Compromise",
      description: "No added sugar. Pure natural energy that lasts.",
      icon: "Wind",
    },
  ],
  socialProof: {
    rating: 4.9,
    servings: "25,000+",
    trustedBy: "Elite Athletes & Wellness Seekers",
  },
  categories: [
    { id: "powders", name: "Powders", sortOrder: 0 },
    { id: "shots", name: "Health Shots", sortOrder: 1 },
  ],
  products: [
    {
      id: "protein_chocolate",
      categoryId: "powders",
      name: "Prax Protein",
      flavor: "Chocolate",
      description: "Multi-source plant protein with 18g protein and 0g sugar per serving.",
      priceNgn: 15999,
      stats: { protein: "18g", calories: "120", sugar: "0g" },
      ingredients: [
        "Soy Protein",
        "Peanut",
        "Flaxseed",
        "Sunflower Protein",
        "Pumpkin Seed",
        "Oat Protein",
        "Chia Seed",
      ],
      image: "/images/products/protein_chocolate.png",
      model: "/models/products/protein_chocolate.glb",
      sortOrder: 0,
      isAvailable: true,
      merchandisingState: "featured",
    },
    {
      id: "soy_powder",
      categoryId: "powders",
      name: "Soybean",
      description:
        "Pure, natural nourishment. 100% organic soybean powder for daily vitality.",
      priceNgn: 5999,
      stats: { weight: "200g", organic: "100%" },
      ingredients: ["100% Organic Soybeans"],
      image: "/images/products/soy_powder.png",
      model: "/models/products/soy_powder.glb",
      sortOrder: 1,
      isAvailable: true,
      merchandisingState: "standard",
    },
    {
      id: "shot_glow",
      categoryId: "shots",
      name: "Glow",
      description:
        "Rich in Vitamin C and anti-inflammatories to brighten skin and strengthen immunity.",
      priceNgn: 1499,
      stats: {},
      ingredients: ["Carrot", "Ginger", "Turmeric", "Orange", "Lime", "Black Pepper"],
      image: "/images/products/shot_glow.png",
      model: "/models/products/shot_glow.glb",
      sortOrder: 0,
      isAvailable: true,
      merchandisingState: "standard",
    },
    {
      id: "shot_immunity",
      categoryId: "shots",
      name: "Immunity",
      description:
        "Antimicrobial boost to flush out toxins and empower your immune system.",
      priceNgn: 1499,
      stats: {},
      ingredients: ["Turmeric", "Ginger", "Cinnamon", "Garlic", "Clove", "Honey", "ACV"],
      image: "/images/products/shot_immunity.png",
      model: "/models/products/shot_immunity.glb",
      sortOrder: 1,
      isAvailable: true,
      merchandisingState: "standard",
    },
    {
      id: "shot_metabolism",
      categoryId: "shots",
      name: "Metabolism",
      description:
        "Promotes gut health and kick-starts digestion with natural probiotics.",
      priceNgn: 1499,
      stats: {},
      ingredients: ["Mint", "Pineapple", "Cucumber", "Spinach", "Chia Seed", "Lime", "Probiotic"],
      image: "/images/products/shot_metabolism.png",
      model: "/models/products/shot_metabolism.glb",
      sortOrder: 2,
      isAvailable: true,
      merchandisingState: "standard",
    },
  ],
  ingredients: [
    {
      id: "soy",
      name: "Soy Bean Protein",
      category: "Proteins",
      role: "core",
      detail: "Complete amino acid profile for muscle synthesis. Highly bioavailable and zero-fillers.",
      benefit: "Muscle Growth & Repair",
      image: "/images/ingredients/soy.png",
      aliases: ["Soy Protein", "100% Organic Soybeans"],
      sortOrder: 0,
    },
    {
      id: "flaxseed",
      name: "Flaxseed",
      category: "Seeds",
      role: "supporting",
      detail: "Rich in omega-3 fatty acids and fiber for heart health.",
      benefit: "Heart Health & Digestion",
      image: "/images/ingredients/flaxseed.png",
      aliases: ["Flaxseed"],
      sortOrder: 1,
    },
    {
      id: "peanut",
      name: "Peanut",
      category: "Proteins",
      role: "supporting",
      detail: "Natural protein source with healthy fats and sustained energy.",
      benefit: "Sustained Energy",
      image: "/images/ingredients/peanut.png",
      aliases: ["Peanut"],
      sortOrder: 2,
    },
    {
      id: "sunflower-protein",
      name: "Sunflower Protein",
      category: "Proteins",
      role: "core",
      detail: "Plant-based protein rich in B vitamins and minerals.",
      benefit: "Vitamin B Boost",
      image: "/images/ingredients/sunflower.png",
      aliases: ["Sunflower Protein"],
      sortOrder: 3,
    },
    {
      id: "oat-protein",
      name: "Oat Protein",
      category: "Proteins",
      role: "supporting",
      detail: "Slow-digesting carbs for sustained energy release.",
      benefit: "Endurance Support",
      image: "/images/ingredients/oat.png",
      aliases: ["Oat Protein"],
      sortOrder: 4,
    },
    {
      id: "pumpkin-seed",
      name: "Pumpkin Seed",
      category: "Seeds",
      role: "core",
      detail: "Magnesium-rich protein for muscle recovery and hormonal balance.",
      benefit: "Muscle Recovery",
      image: "/images/ingredients/pumpkin.png",
      aliases: ["Pumpkin Seed"],
      sortOrder: 5,
    },
    {
      id: "chia-seeds",
      name: "Chia Seeds",
      category: "Seeds",
      role: "supporting",
      detail: "Omega-3 fatty acids and sustained hydration through fiber rich structure.",
      benefit: "Hydration & Omega-3",
      image: "/images/ingredients/chia.png",
      aliases: ["Chia Seed", "Chia Seeds"],
      sortOrder: 6,
    },
    {
      id: "turmeric",
      name: "Turmeric",
      category: "Botanicals",
      role: "core",
      detail: "Potent anti-inflammatory and immune-focused adaptogen.",
      benefit: "Inflammation Defense",
      image: "/images/ingredients/tumeric.png",
      aliases: ["Turmeric"],
      sortOrder: 7,
    },
  ],
  homeSections: [
    {
      sectionKey: "hero",
      sectionType: "hero",
      sortOrder: 0,
      isEnabled: true,
      eyebrow: "Plant-Based Performance",
      heading: "Natural Energy",
      body: "Hero stage and entry point for the catalog.",
      settings: {
        badgeItems: ["Plant-Based", "Clean Ingredients", "Easy Digestion"],
        primaryActionLabel: "Start Your Order",
        secondaryActionLabel: "View Ingredients",
      },
    },
    {
      sectionKey: "problem",
      sectionType: "problem_statement",
      sortOrder: 1,
      isEnabled: true,
      eyebrow: "The Problem",
      heading: "Most supplements are compromise disguised as fuel.",
      body: "Current problem framing section.",
      settings: {},
    },
    {
      sectionKey: "solution",
      sectionType: "science_strip",
      sortOrder: 2,
      isEnabled: true,
      eyebrow: "The System",
      heading: "Meet House of Prax",
      body: "Brand trust and flagship explanation section.",
      settings: {
        featuredProductId: "protein_chocolate",
      },
    },
    {
      sectionKey: "benefits",
      sectionType: "benefit_grid",
      sortOrder: 3,
      isEnabled: true,
      eyebrow: "Capabilities",
      heading: "Built for Real Performance.",
      body: "Four-pill benefit grid.",
      settings: {},
    },
    {
      sectionKey: "ingredients",
      sectionType: "ingredient_story",
      sortOrder: 4,
      isEnabled: true,
      eyebrow: "Transparency",
      heading: "Nothing Hidden. Nothing Fake.",
      body: "Ingredient explorer with formula lens.",
      settings: {},
    },
    {
      sectionKey: "how_it_works",
      sectionType: "process_steps",
      sortOrder: 5,
      isEnabled: true,
      eyebrow: "The Ritual",
      heading: "Simple Daily Fuel.",
      body: "Preparation ritual and product use guidance.",
      settings: {
        image: "/images/how-it-works.png",
      },
    },
    {
      sectionKey: "lifestyle",
      sectionType: "lifestyle_gallery",
      sortOrder: 6,
      isEnabled: true,
      eyebrow: "Life in HOP",
      heading: "Fuel Your Training.",
      body: "Lifestyle image gallery.",
      settings: {
        gallery: [
          { src: "/images/lifestyle/gym.png", alt: "Workout session", span: "row-span-2" },
          { src: "/images/lifestyle/smoothie.png", alt: "Smoothie prep", span: "" },
          { src: "/images/lifestyle/desk.png", alt: "Desk work", span: "" },
          { src: "/images/lifestyle/recovery.png", alt: "Post-gym recovery", span: "col-span-2" },
        ],
      },
    },
    {
      sectionKey: "products",
      sectionType: "featured_products",
      sortOrder: 7,
      isEnabled: true,
      eyebrow: "Products",
      heading: "Choose Your Fuel.",
      body: "Interactive product selector and add-to-cart surface.",
      settings: {
        defaultCategoryId: "powders",
        defaultProductId: "protein_chocolate",
      },
    },
    {
      sectionKey: "reviews",
      sectionType: "review_highlight",
      sortOrder: 8,
      isEnabled: true,
      eyebrow: "Social Proof",
      heading: "Trusted by the Driven.",
      body: "Community and quality trust section.",
      settings: {},
    },
    {
      sectionKey: "cta",
      sectionType: "final_cta",
      sortOrder: 9,
      isEnabled: true,
      eyebrow: "Get Started",
      heading: "Upgrade Your Protein.",
      body: "Final conversion section.",
      settings: {
        defaultProductId: "protein_chocolate",
      },
    },
  ],
};
